class QuestionModel {
  final String id;
  final DateTime createdAt;
  final DateTime? answeredAt;
  String title;
  Sender sender;
  String? answerText;
  final bool isDeleted;
  final List<String> images;
  final bool isAnonymous;
  int likesCount;
  final int commentCount;
  final Receiver receiver;
  bool isLiked;
  bool isPinned;

  QuestionModel({
    required this.id,
    required this.createdAt,
    this.answeredAt,
    required this.title,
    required this.sender,
    this.answerText,
    this.isDeleted = false,
    this.images = const [],
    this.isAnonymous = false,
    this.likesCount = 0,
    this.commentCount = 0,
    required this.receiver,
    this.isLiked = false,
    this.isPinned = false,
  });

  factory QuestionModel.fromJson(Map<String, dynamic> json) {
    return QuestionModel(
      id: json['id'] ?? '',
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : DateTime.now(),
      answeredAt: json['answered_at'] != null
          ? DateTime.parse(json['answered_at'])
          : null,
      title: json['title'] ?? '',
      // Handle nested sender object from Supabase join
      sender: json['sender'] != null
          ? Sender.fromJson(json['sender'])
          : Sender(id: '', name: '', userName: '', token: ''),
      answerText: json['answer_text'], // snake_case
      isDeleted: json['is_deleted'] ?? false, // snake_case
      images: List<String>.from(json['images'] ?? []),
      isAnonymous: json['is_anonymous'] ?? false, // snake_case
      likesCount: json['likes_count'] ?? 0, // snake_case
      commentCount: json['comments_count'] ?? 0, // snake_case
      // Handle nested receiver object from Supabase join
      receiver: json['receiver'] != null
          ? Receiver.fromJson(json['receiver'])
          : Receiver(id: '', image: '', name: '', userName: '', token: ''),
      isPinned: json['is_pinned'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Usually generated by DB
      'created_at': createdAt.toIso8601String(),
      'answered_at': answeredAt?.toIso8601String(),
      'title': title,
      'sender_id': sender.id, // For inserting, we typically send just ID
      'answer_text': answerText,
      'is_deleted': isDeleted,
      'images': images,
      'is_anonymous': isAnonymous,
      'likes_count': likesCount,
      'comments_count': commentCount,
      'receiver_id': receiver.id, // For inserting, we typically send just ID
      'is_pinned': isPinned,
    };
  }
}

class Sender {
  final String id;
  final String name;
  final String userName;
  final String? image;
  final String token;
  final bool isVerified;

  Sender({
    required this.id,
    required this.name,
    required this.userName,
    required this.token,
    this.image,
    this.isVerified = false,
  });

  factory Sender.fromJson(Map<String, dynamic> json) {
    return Sender(
      id: json['id']?.toString() ?? '',
      name: json['name'] ?? '',
      image: json['image'],
      userName: json['username'] ?? '', // snake_case in users table
      token: json['token'] ?? '',
      isVerified: json['is_verified'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'image': image,
      'username': userName,
      'token': token,
    };
  }
}

class Receiver {
  final String id;
  final String name;
  final String token;
  final String image;
  final String userName;
  final bool isVerified;

  Receiver({
    required this.id,
    required this.image,
    required this.name,
    required this.userName,
    required this.token,
    this.isVerified = false,
  });

  factory Receiver.fromJson(Map<String, dynamic> json) {
    return Receiver(
      id: json['id']?.toString() ?? '',
      name: json['name'] ?? '',
      image: json['image'] ?? '',
      userName: json['username'] ?? '', // snake_case in users table
      token: json['token'] ?? '',
      isVerified: json['is_verified'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'image': image,
      'username': userName,
      'token': token,
    };
  }
}
