// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_tlqSqqi9BYvt6NYC0cdHSHfiyNSEho',
    appId: '1:623808187900:android:47f1e0531eea8b98b0b679',
    messagingSenderId: '623808187900',
    projectId: 'domandito-281cc',
    storageBucket: 'domandito-281cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT83frmFc2vOBBrKM0H4acuBVe3LIzi74',
    appId: '1:623808187900:ios:62ef5164b9197963b0b679',
    messagingSenderId: '623808187900',
    projectId: 'domandito-281cc',
    storageBucket: 'domandito-281cc.firebasestorage.app',
    iosClientId: '623808187900-vhlcaipk394s763irf23ltpcn2ernhj8.apps.googleusercontent.com',
    iosBundleId: 'com.m0ustafamahm0ud.domandito',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRrWvFHylTHJv9-UTE8lQiz5vtUcRUZ0Y',
    appId: '1:623808187900:web:3a770f5099e00d8ab0b679',
    messagingSenderId: '623808187900',
    projectId: 'domandito-281cc',
    authDomain: 'domandito-281cc.firebaseapp.com',
    storageBucket: 'domandito-281cc.firebasestorage.app',
    measurementId: 'G-69NKWMSC4F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT83frmFc2vOBBrKM0H4acuBVe3LIzi74',
    appId: '1:623808187900:ios:fcba1a1124b96e3db0b679',
    messagingSenderId: '623808187900',
    projectId: 'domandito-281cc',
    storageBucket: 'domandito-281cc.firebasestorage.app',
    iosClientId: '623808187900-c8oha1qpgdstqhqoqbud6p45hjj60cdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.domandito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRrWvFHylTHJv9-UTE8lQiz5vtUcRUZ0Y',
    appId: '1:623808187900:web:d0c0c548d536de9eb0b679',
    messagingSenderId: '623808187900',
    projectId: 'domandito-281cc',
    authDomain: 'domandito-281cc.firebaseapp.com',
    storageBucket: 'domandito-281cc.firebasestorage.app',
    measurementId: 'G-B2CR5GESCZ',
  );

}