import 'package:domandito/modules/signin/models/user_model.dart';

class NotificationModel {
  final String id;
  final DateTime createdAt;
  final String userId;
  final String? senderId;
  final String type; // 'like', 'answer', 'question', 'follow'
  final String? entityId;
  final String? title;
  final String? body;
  final bool isRead;
  final UserModel? sender;

  NotificationModel({
    required this.id,
    required this.createdAt,
    required this.userId,
    this.senderId,
    required this.type,
    this.entityId,
    this.title,
    this.body,
    this.isRead = false,
    this.sender,
  });

  factory NotificationModel.fromJson(Map<String, dynamic> json) {
    return NotificationModel(
      id: json['id'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
      userId: json['user_id'] as String,
      senderId: json['sender_id'] as String?,
      type: json['type'] as String,
      entityId: json['entity_id'] as String?,
      title: json['title'] as String?,
      body: json['body'] as String?,
      isRead: json['is_read'] as bool? ?? false,
      sender: json['sender'] != null
          ? UserModel.fromMap(json['sender'] as Map<String, dynamic>)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Generated by DB
      // 'created_at': createdAt.toIso8601String(), // Generated by DB
      'user_id': userId,
      'sender_id': senderId,
      'type': type,
      'entity_id': entityId,
      'title': title,
      'body': body,
      'is_read': isRead,
    };
  }
}
